name: Build and Push to GHCR

on:
  workflow_dispatch:

jobs:
    build-and-push:
        name: Build and Push to GHCR
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        environment: ghcr
        steps:
          - name: Checkout code
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

          - name: Login to GHCR
            uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

            # need to lowercase repository because ghcr requires reference in lowercase
          - name: Get repository name
            run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
            id: repo

          - name: Build and push Docker images
            uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
            with:
              context: ./server
              file: ./server/Dockerfile
              push: true
              tags: "ghcr.io/${{ steps.repo.outputs.REPO }}:server-${{ github.sha }}"

          - name: Build and push All-in-One Docker image
            uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: |
                ghcr.io/${{ steps.repo.outputs.REPO }}:${{ github.sha }}
                ghcr.io/${{ steps.repo.outputs.REPO }}:latest
