name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release. Must be in the CHANGELOG.md file. Example: 1.0.0'
        required: true
      sha:
        description: 'Commit SHA to release. Example: 7dec363daaca95c59f68607ac1f29a12bc0b195b'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # always read the changelog in main
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: 'main'

      - name: Read changelog
        id: changelog
        uses: mindsers/changelog-reader-action@b97ce03a10d9bdbb07beb491c76a5a01d78cd3ef # v2.2.2
        with:
          validation_level: warn
          version: ${{ inputs.version }}

      - name: Create or update release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          name: ${{ steps.changelog.outputs.version }}
          tag: v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
          commit: ${{ inputs.sha }}
          prerelease: false
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
